"""Record post-campaign validation without launching any final inference.

The practical suite contains tiny scientific wiring tests. No scientific batch
is run, resumed or regenerated by this harness. Use a new output ID each time.
"""

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from publication.contracts import sha256_file, utc_now  # noqa: E402


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    output = (ROOT / args.output).resolve()
    if not output.is_relative_to(ROOT / "publication/validation"):
        raise ValueError("Validation output must be inside publication/validation")
    output.mkdir(parents=True, exist_ok=False)
    commands = [
        ("unit_integration_smoke", [sys.executable, "scripts/run_ci_tests.py"], 0),
        ("lint", [sys.executable, "-m", "ruff", "check", "."], 0),
        ("static", [sys.executable, "scripts/static_validate.py"], 0),
        ("historical_baseline_artifacts", [sys.executable, "scripts/validate_hardened_artifacts.py"], 0),
        ("synthesis_integrity", [sys.executable, "scripts/build_publication_synthesis.py", "--check"], 0),
        ("paper_release_not_approved", [sys.executable, "scripts/validate_publication_release.py"], 1),
    ]
    checks = []
    for name, command, expected in commands:
        started = time.monotonic()
        with (output / f"{name}.stdout.txt").open("w") as stdout, (output / f"{name}.stderr.txt").open("w") as stderr:
            result = subprocess.run(command, cwd=ROOT, stdout=stdout, stderr=stderr, check=False)
        checks.append({"check": name, "command": command, "return_code": result.returncode,
                       "expected_return_code": expected, "passed": result.returncode == expected,
                       "seconds": time.monotonic() - started})
        print(f"{name}: exit={result.returncode}, expected={expected}", flush=True)
    source_paths = ["src/publication/synthesis.py", "scripts/build_publication_synthesis.py",
                    "tests/test_publication_synthesis.py", "tests/test_confirmatory_campaign.py",
                    "tests/manual/validate_post_campaign_synthesis.py",
                    "reports/publication_synthesis/tcc_evidence_v1/artifact_manifest.json",
                    "requirements.txt", "environment.yml", "pyproject.toml"]
    missing_sources = [name for name in source_paths if not (ROOT / name).is_file()]
    payload = {"schema_version": "post-campaign-validation-v1", "generated_at_utc": utc_now(),
               "status": "passed" if all(row["passed"] for row in checks) and not missing_sources else "failed", "checks": checks,
               "missing_sources": missing_sources,
               "scope": "Local tests and evidence integrity; expected release rejection is NOT release approval; no clean-room claim",
               "code_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT).decode().strip(),
               "source_checksums": {name: sha256_file(ROOT / name) for name in source_paths if name not in missing_sources},
               "logs": {path.name: sha256_file(path) for path in output.iterdir() if path.is_file()}}
    (output / "validation.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8", newline="\n")
    if payload["status"] != "passed":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
